version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet build "./Isobar.Fm.Api/Isobar.Fm.Api.sln" -c Release -o /app
      - run: dotnet test "./Isobar.Fm.Api/Isobar.Fm.Tests.Units/Isobar.Fm.Tests.Units.csproj" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - codecov/upload:
          file: "./Isobar.Fm.Api/Isobar.Fm.Tests.Units/coverage.opencover.xml" 